DROP TABLE "EDM"."NOTIFY_PERIOD";

CREATE TABLE "EDM"."NOTIFY_PERIOD"(

  PERIOD        VARCHAR(1)      NOT NULL,
  DESCRIPTION   VARCHAR(50)     NOT NULL
)

TABLESPACE "EDM_TS";

ALTER TABLE "EDM"."NOTIFY_PERIOD" ADD CONSTRAINT PK_NOTIFY_PERIOD PRIMARY KEY(PERIOD);
ALTER TABLE "EDM"."NOTIFY_PERIOD" OWNER to "EDM";

DELETE FROM "EDM"."NOTIFY_PERIOD" WHERE PERIOD IN ('D', 'W', 'M', 'Y');

INSERT INTO "EDM"."NOTIFY_PERIOD"(PERIOD, DESCRIPTION) VALUES('D', 'Day(s)');
INSERT INTO "EDM"."NOTIFY_PERIOD"(PERIOD, DESCRIPTION) VALUES('W', 'Week(s)');
INSERT INTO "EDM"."NOTIFY_PERIOD"(PERIOD, DESCRIPTION) VALUES('M', 'Month(s)');
INSERT INTO "EDM"."NOTIFY_PERIOD"(PERIOD, DESCRIPTION) VALUES('Y', 'Year(s)');

COMMIT;