DROP TABLE "EDM"."USERS_TYPES";
CREATE TABLE "EDM"."USERS_TYPES"(

  USER_TYPE     VARCHAR(4) NOT NULL,
  DESCRIPTION   VARCHAR(50)

)
TABLESPACE "EDM_TS";

ALTER TABLE "EDM"."USERS_TYPES" ADD CONSTRAINT PK_USERS_TYPES PRIMARY KEY(USER_TYPE);
ALTER TABLE "EDM"."USERS_TYPES" OWNER to "EDM";

DELETE FROM "EDM"."USERS_TYPES" WHERE USER_TYPE IN ('REG','PREM');
INSERT INTO "EDM"."USERS_TYPES" (USER_TYPE, DESCRIPTION) VALUES('REG' , 'Regular');
INSERT INTO "EDM"."USERS_TYPES" (USER_TYPE, DESCRIPTION) VALUES('PREM', 'Premium');

COMMIT;
