DROP TABLE "EDM"."USER_ITEMS";

CREATE TABLE "EDM"."USER_ITEMS"(

  SEQ_USER          INTEGER     NOT NULL,
  SEQ_ITEM          INTEGER     NOT NULL,
  ITEM_NAME         VARCHAR(50)         ,
  DESCRIPTION       VARCHAR(250)        ,
  SEQ_CATEG         INTEGER             ,
  SEQ_LOCATION      INTEGER             ,
  ITEM_STATUS       VARCHAR(1)          ,
  PURCHASE_CREATED  DATE                ,
  EXPIRY_DATE       DATE                ,
  NOTIFY_BEFORE     INTEGER             ,
  NOTIFY_PERIOD     VARCHAR(1)          ,
  ADD_COMMENTS      VARCHAR(255)
)

TABLESPACE "EDM_TS";

ALTER TABLE "EDM"."USER_ITEMS" ADD CONSTRAINT PK_USER_ITEM          PRIMARY KEY(SEQ_USER, SEQ_ITEM);
ALTER TABLE "EDM"."USER_ITEMS" ADD CONSTRAINT FK_USER_ITEM          FOREIGN KEY(SEQ_USER) REFERENCES "EDM"."USERS"(SEQ_USER);
ALTER TABLE "EDM"."USER_ITEMS" ADD CONSTRAINT FK_ITEM_CATEG         FOREIGN KEY(SEQ_CATEG) REFERENCES "EDM"."USER_ITEMS_CATEGORIES"(SEQ_CATEG);
ALTER TABLE "EDM"."USER_ITEMS" ADD CONSTRAINT FK_ITEM_LOCATION      FOREIGN KEY(SEQ_LOCATION) REFERENCES "EDM"."USER_ITEMS_LOCATIONS"(SEQ_LOCATION);
ALTER TABLE "EDM"."USER_ITEMS" ADD CONSTRAINT FK_ITEM_NOTIFY_PERIOD FOREIGN KEY(NOTIFY_PERIOD) REFERENCES "EDM"."NOTIFY_PERIOD"(PERIOD);
ALTER TABLE "EDM"."USER_ITEMS" ADD CONSTRAINT FK_ITEM_STATUS        FOREIGN KEY(ITEM_STATUS) REFERENCES "EDM"."ITEMS_STATUS"(STATUS);
ALTER TABLE "EDM"."USER_ITEMS" OWNER to "EDM";