DROP TABLE "EDM"."USERS";

CREATE TABLE "EDM"."USERS"(

  USER_ID           VARCHAR(50) NOT NULL,
  USER_PASS         VARCHAR(50) NOT NULL,
  FIRST_NAME        VARCHAR(50),
  LAST_NAME         VARCHAR(50),
  COUNTRY           VARCHAR(3),
  DATE_CREATED      TIMESTAMP,
  LAST_LOGIN        TIMESTAMP,
  USER_TYPE         VARCHAR(4),
  USER_STATUS       VARCHAR(1)
)

TABLESPACE "EDM_TS";

ALTER TABLE "EDM"."USERS" ADD CONSTRAINT PK_USERS_ID PRIMARY KEY(USER_ID);
ALTER TABLE "EDM"."USERS" OWNER to "EDM";