DROP TABLE "EDM"."USER_ITEMS_CATEGORIES";

CREATE TABLE "EDM"."USER_ITEMS_CATEGORIES"(
 SEQ_USER      INTEGER NOT NULL       ,
 SEQ_CATEG     INTEGER NOT NULL UNIQUE,
 DESCRIPTION   VARCHAR(250) 
)

TABLESPACE "EDM_TS";

ALTER TABLE "EDM"."USER_ITEMS_CATEGORIES" ADD CONSTRAINT PK_ITEM_CATEG PRIMARY KEY(SEQ_USER, SEQ_CATEG);
ALTER TABLE "EDM"."USER_ITEMS_CATEGORIES" OWNER to "EDM";