DROP TABLE "EDM"."USERS_STATUS";
CREATE TABLE "EDM"."USERS_STATUS"(

  STATUS       VARCHAR(1) NOT NULL,
  DESCRIPTION  VARCHAR(50)

)
TABLESPACE "EDM_TS";

ALTER TABLE "EDM"."USERS_STATUS" ADD CONSTRAINT PK_USERS_STATUS PRIMARY KEY(STATUS);
ALTER TABLE "EDM"."USERS_STATUS" OWNER to "EDM";

DELETE FROM "EDM"."USERS_STATUS" WHERE STATUS IN ('A','I','S');
INSERT INTO "EDM"."USERS_STATUS" (STATUS, DESCRIPTION) VALUES('A', 'Active');
INSERT INTO "EDM"."USERS_STATUS" (STATUS, DESCRIPTION) VALUES('I', 'Inactive');
INSERT INTO "EDM"."USERS_STATUS" (STATUS, DESCRIPTION) VALUES('S', 'Suspended');

COMMIT;